name: "Conversation Rewards"
description: "Compute rewards for contributors' discussion on issues that are closed as complete."
inputs:
  stateId:
    description: "State Id"
  eventName:
    description: "Event Name"
  eventPayload:
    description: "Event Payload"
  settings:
    description: "Settings"
  authToken:
    description: "Auth Token"
  ref:
    description: "Ref"
outputs:
  result:
    description: "The result containing all the rewards of the users"
    value: ${{ steps.main.outputs.result }}
runs:
  using: 'node20'
  main: 'dist/index.js'
