name: Build Action

on:
  push:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - uses: actions/checkout@v4

      - name: Install & Build
        run: |
          yarn install --immutable --immutable-cache --check-cache
          yarn build

      - name: Commit and Push generated dist
        run: |
          git config --global user.name 'ubiquity-os[bot]'
          git config --global user.email 'ubiquity-os[bot]@users.noreply.github.com'
          git add ./dist/\*
          if [ -n "$(git diff-index --cached --name-only HEAD)" ]; then
            git commit -m "chore: updated dist" || echo "Lint-staged check failed"
            git push origin HEAD:${{ github.ref_name }}
          else
            echo "No changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}