name: Compute Rewards

on:
  workflow_dispatch:
    inputs:
      stateId:
        description: "State Id"
      eventName:
        description: "Event Name"
      eventPayload:
        description: "Event Payload"
      settings:
        description: "Settings"
      authToken:
        description: "Auth Token"
      ref:
        description: "Ref"

jobs:
  compute:
    name: Rewards
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      X25519_PRIVATE_KEY: ${{ secrets.X25519_PRIVATE_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
      NFT_MINTER_PRIVATE_KEY: ${{ secrets.NFT_MINTER_PRIVATE_KEY }}
      NFT_CONTRACT_ADDRESS: ${{ secrets.NFT_CONTRACT_ADDRESS }}
      PERMIT_FEE_RATE: ${{ secrets.PERMIT_FEE_RATE }}
      PERMIT_TREASURY_GITHUB_USERNAME: ${{ secrets.PERMIT_TREASURY_GITHUB_USERNAME }}
      PERMIT_ERC20_TOKENS_NO_FEE_WHITELIST: ${{ secrets.PERMIT_ERC20_TOKENS_NO_FEE_WHITELIST }}

    steps:
      - name: Post starting comment to issue
        uses: actions/github-script@v7
        id: post-comment
        with:
          github-token: ${{ inputs.authToken }}
          script: |
            const comment_body = '\`\`\`diff\n+ Evaluating results. Please wait...';
            const obj = ${{ inputs.eventPayload }}
            if (obj.issue && "${{ inputs.eventName }}" === "issues.closed" && obj.issue.state_reason === "completed") {
              const response = await github.rest.issues.createComment({
                owner: obj.repository.owner.login,
                repo: obj.repository.name,
                issue_number: obj.issue.number,
                body: comment_body,
              });
              core.setOutput('comment_id', response.data.id);
            }

      - name: Set environment variable
        run: echo "COMMENT_ID=${{ steps.post-comment.outputs.comment_id }}" >> $GITHUB_ENV

      - run: ${{ toJSON(inputs) }}
        shell: cat {0}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.10.0"

      - name: Generate Rewards
        uses: ./
