name: "Update Configuration"

on:
  workflow_dispatch:
  push:

jobs:
  update:
    name: "Update Configuration in manifest.json"
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: Meniole/action-deploy-plugin@feat/init-repo
#        with:
#          schema-path: "${{ github.workspace }}/src/types/plugin-inputs.js"
#          commit-message: "chore: update"
#          manifest-path: "${{ github.workspace }}/manifest.json"
#        env:
#          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
